# **Nivel 1**
## Ejercicio 1: Selección de personas

In [11]:
import pandas as pd

Primero de todo, tenemos que pedir los datos que necesitamos de cada candidato
para luego poder obtener la información que RRHH nos ha solicitado.
Esta información, debemos guardarla en un diccionario para poder efectuar los calculos.


---


    
**FUNCIÓN** obtener_datos:
1. Pedir nombre y apellidos (texto - str)
2. Pedir número de teléfono de contacto (texto- str)
3. Pedir los años de experiencia (num entero ≥ 0)
4. Pedir la puntuación en catalán (num entero 0-3)
5. Pedir la puntuación en Excel (num entero 0-3)
6. Pedir el título académico (num entero 0-3)
7. Devolver un diccionario con todos los datos

In [20]:
def obtener_datos(numero_candidato):

  print(f"CANDIDATO {numero_candidato} DE 10")
  nombre = input("Introduce tu nombre y primer apellido: ")
  telefono = input("Introduce tu número de teléfono: ") # definimos que sea un numero entero

  # que nos de un error cuando el valor sea negativo
  try:
    experiencia = int(input("Introduce tus años de experiencia: "))
  except ValueError:
    experiencia < 0

  # que nos de un error cuando el valor no esté entre 0 y 3
  try:
    catalan = int(input("Introduce tu puntuación en catalán (0 = sin conocimientos // 1 = hasta el nivel B1 // 2 = nivel B2 // 3 = C1 o superior): "))
  except ValueError:
    catalan < 0 or catalan > 3

  try:
    excel = int(input("Introduce tu puntuación en Excel (0 = nivel básico // 1 = uso de funciones // 2 = tablas dinámicas // 3 = Visual Basic y macros):  "))
  except ValueError:
    excel < 0 or excel > 3

  try:
    titulo = int(input("Introduce tu título académico (0 = ESO // 1 = Título de formación profesional // 2 = Universidad // 3 = Máster o título superior) "))
  except ValueError:
    titulo < 0 or titulo > 3

  # que guarde los datos
  datos = {
        "nombre": nombre,
        "telefono": telefono,
        "experiencia": experiencia,
        "catalan": catalan,
        "excel": excel,
        "titulo": titulo
         }
  return datos

Comprobamos que todos los datos introducidos manualmente por los candidatos sean válidos, estén completos y que estén dentro del rango que RRHH nos ha dado.
Si todo el correcto, necesitamos que estos datos se guarden. Si en algún momento se introducen datos que no complen los requisitos dado, saldrá en la pantalla un error.


---




**FUNCIÓN** validar_datos(datos del candidato obtenidos en el código anterior):
  1. Comprobar que "nombre" no esté vacío
  2. Comprobar que "apellidos" no esté vacío
  3. Comprobar que "telefono no esté vacío
  4. Comprobar que "experiencia" sea >= 0
  5. Comprobar que catalan, excel y titulo estén entre 0 y 3
  6. Si todo es válido →  True
  6. Si hay un error → muestra un mensaje y devuelve False

In [12]:
def validar_datos(datos):

  if not datos["nombre"]:
        print("ERROR: Este campo no puede estar vacio")
        return False

  if not datos["telefono"]:
        print("ERROR: Este campo no puede estar vacio")
        return False

  if datos["experiencia"] < 0:
        print("ERROR: Los años de experiencia no pueden ser negativos")
        return False

  if datos["catalan"] < 0 or datos["catalan"] > 3:
        print("ERROR: La puntuación de catalán debe estar entre 0 y 3")
        return False

  if datos["excel"] < 0 or datos["excel"] > 3:
        print("ERROR: La puntuación de excel debe estar entre 0 y 3")
        return False

  if datos["titulo"] < 0 or datos["titulo"] > 3:
        print("ERROR: La puntuación del titulo debe estar entre 0 y 3")
        return False

  return True

Calcular la puntuación total de cada candidato con la fórmula que RRHH nos ha pedido:
puntuación total = años de experiencia * 1.5 + nivel catalán + nivel excel + título


---



**FUNCIÓN** calcular_puntuacion(con los datos obtenidos del candidato):
  1. Calcular años_experiencia = experiencia * 1,5
  2. Sumar catalan + excel + titulo
  3. puntuacion_total = años_experiencia + catalan + excel + titulo
  4. Devolver puntuacion_total y que quede guardada.

In [13]:
def calcular_puntuacion(datos):
  años_experiencia = datos["experiencia"] * 1.5
  puntuacion_total = años_experiencia + datos["catalan"] + datos["excel"] + datos["titulo"]
  return puntuacion_total

Ahora necesitamos clasificar a los candidatos inscritos según los umbrales establecidos por la empresa.


---


**FUNCIÓN** clasificar_candidato(puntuacion_total obtenida de la función anterior):
  1. Si la puntuación total >= 12  → devolver "Prioridad alta"
  2. Si la puntuación total 8 <= o < 12 → devolver "Candidato adecuado"
  3. Si la puntuación total < 8   → devolver "No prioritario"

  Utilizamos condicionales para generar esta clasificación.

In [14]:
def clasificar_candidato(puntuacion_total):
    if puntuacion_total >= 12:
      return "Prioridad alta", 1          # le damos un orden, orden 1 para después poder ordenar
    elif puntuacion_total <= 8 and puntuacion_total < 12:
      return "Candidato adecuado", 2      # orden 2
    else:
      return "No prioritario", 3          # orden 3

Necesitamos, para más tarde crear un informe, mostrar los resultados obtenidos de cada candidato una vez rellenado el formulario.


---


**FUNCIÓN** mostrar_individual(datos_candidato, puntuacion_total, clasificaciónde la función anterior):
  1. Mostrar nombre y apellidos del candidato
  2. Mostrar puntuación total que ya ha sido calculada
  3. Mostrar clasificación recibida por la función anterior

In [15]:
def mostrar_individual(datos, puntuacion_total, clasificacion):
    print(f"Candidato/a: {datos["nombre"]}")
    print(f"Puntuación:  {puntuacion_total}")
    print(f"Categoria: {clasificacion}")

Por último, tenemos que generar un informe final con el nombre, apellidos, teléfono, puntuación y prioridad de todos los candidatos inscritos para que RRHH pueda llamarlos sin necesidad que recurrir a nosotros para obtener los datos.
Estos candidatos deben estar ordenados por puntuación de mayor a menor, por lo tanto, hay qué definir cómo ordenarlos y tener en cuenta los empates.



---


**FUNCIÓN** mostrar_informe(con todos los candidatos que se han inscrito, hasta un máximo de 10 pax):
  1. Obtener los datos guardados
  2. Definir el orden de "*Prioridad Alta*" a "*No prioritario*"
  3. Ordenar los 10 candidatos (Tener en cuenta los empates)
  4. Mostrar los datos que se piden de cada candidato:  Nombre, teléfono, puntuación y tipo de prioridad.
  5. Trasnformar en una tabla (dataframe) para que sea más fácil de visualizar.

In [16]:
def mostrar_informe(lista_candidatos):
  import pandas as pd # para luego poder transfromar en un dataframe el listado de los candidatos

  l = len(lista_candidatos)
  for i in range(l - 1):
        for j in range(l - 1 - i):
            candidato_a = lista_candidatos[j]
            candidato_b = lista_candidatos[j + 1]

            # Comparar por prioridad primero
            if candidato_a["orden"] > candidato_b["orden"]:
                lista_candidatos[j] = candidato_b
                lista_candidatos[j + 1] = candidato_a
            elif candidato_a["orden"] == candidato_b["orden"]:
                # Empate en prioridad: mayor puntuación primero
                if candidato_a["puntuacion"] < candidato_b["puntuacion"]:
                    lista_candidatos[j] = candidato_b
                    lista_candidatos[j + 1] = candidato_a

    # Mostrar el informe
  print("\n")
  print("-------------------------------------")
  print("INFORME FINAL – PROCESO DE SELECCIÓN")
  print("-------------------------------------")

  lista_candidatos_df = pd.DataFrame(lista_candidatos)
  display(lista_candidatos_df)

  print("-------------------------------------")
  print("Fin del informe.")
  print("-------------------------------------")

  Por último definimos la **funció principal** que combina todas las funciones anteriores y ejecutará el programa que nos han pedido de una manera eficaz.


---
**FUNCIÓN** main_seleccion():
  1. Crear una lista de candidatos que esté vacia para después añadir los canditatos inscritos.
  2. Añadir un limite a la lista, máximo 10.
  3. Obtener los datos de los candidatos
  4. Validad los datos: Si todos están OK, continuar. Si no son válido, volver a empezar.
  5. Calculamos la puntuación de cada candidato.
  6. Clasificarlos por prioridad.
  7. Mostrar los datos individuales.
  8. Los añadimos a la lsita creada en el paso 1.
  9. Ordenamos la lista.
  10. Cuando la lista haya llegado a su límite, esté con exactamente 10 candidatos, mostrar el informe final con los datos que nos han pedido.

In [21]:
def main_selection():

    print("-----------------------------------------------------")
    print("SISTEMA DE INSCRIPCIÓN – OFERTA DE EMPLEO INTERNA")
    print("Solo se aceptan las primeras 10 solicitudes.")
    print("-----------------------------------------------------")

    lista_candidatos = []
    numero_candidato = 1

    while numero_candidato <= 10:

        # 1. Obtener datos en bruto
        datos = obtener_datos(numero_candidato)

        # 2. Validar datos; si hay error, repetir sin contar la inscripción
        valido = validar_datos(datos)
        if valido == False:
            print("Por favor, vuelve a introducir los datos correctamente.")
            continue  # Repetir sin sumar el valor al contador

        # 3. Calcular puntuación
        puntuacion = calcular_puntuacion(datos)

        # 4. Clasificar candidato
        clasificacion, orden = clasificar_candidato(puntuacion)

        # 5. Mostrar resultado individual
        mostrar_individual(datos, puntuacion, clasificacion)

        # 6. Guardar candidato en la lista
        candidato = {
            "nombre": datos["nombre"],
            "telefono": datos["telefono"],
            "puntuacion": puntuacion,
            "clasificacion": clasificacion,
            "orden": orden
        }
        lista_candidatos.append(candidato)

        numero_candidato = numero_candidato + 1

    # 7. Mostrar informe final con los 10 candidatos
    print("Se han registrado 10 candidatos.")
    mostrar_informe(lista_candidatos)

In [ ]:
#COMPROBAMOS EL PROGRAMA
main_selection()

-----------------------------------------------------
SISTEMA DE INSCRIPCIÓN – OFERTA DE EMPLEO INTERNA
Solo se aceptan las primeras 10 solicitudes.
-----------------------------------------------------
CANDIDATO 1 DE 10
Candidato/a: Laura Serra
Puntuación:  18.0
Categoria: Prioridad alta
CANDIDATO 2 DE 10
Candidato/a: Clara Gómez
Puntuación:  12.5
Categoria: Prioridad alta
CANDIDATO 3 DE 10
Candidato/a: Sergio López
Puntuación:  10.5
Categoria: No prioritario
CANDIDATO 4 DE 10
ERROR: La puntuación de catalán debe estar entre 0 y 3
Por favor, vuelve a introducir los datos correctamente.
CANDIDATO 4 DE 10
Candidato/a: Marta Ruiz
Puntuación:  9.0
Categoria: No prioritario
CANDIDATO 5 DE 10
Candidato/a: Marc Vidal
Puntuación:  18.0
Categoria: Prioridad alta
CANDIDATO 6 DE 10
Candidato/a: Júlia Romero
Puntuación:  15.5
Categoria: Prioridad alta
CANDIDATO 7 DE 10
Candidato/a: Pol Navarro
Puntuación:  13.0
Categoria: Prioridad alta
CANDIDATO 8 DE 10
Candidato/a: David Ferrer
Puntuación:  6.0
Categoria: Candidato adecuado
CANDIDATO 9 DE 10
Candidato/a: Anna Paredes
Puntuación:  4.5
Categoria: Candidato adecuado
CANDIDATO 10 DE 10
Candidato/a: Anibal Paredes
Puntuación:  4.5
Categoria: Candidato adecuado
Se han registrado 10 candidatos.


-------------------------------------
INFORME FINAL – PROCESO DE SELECCIÓN
-------------------------------------

           nombre   telefono  puntuacion       clasificacion  orden
0     Laura Serra  608112233        18.0      Prioridad alta      1
1      Marc Vidal  612443322        18.0      Prioridad alta      1
2    Júlia Romero  677998877        15.5      Prioridad alta      1
3     Pol Navarro  699554433        13.0      Prioridad alta      1
4     Clara Gómez  655221199        12.5      Prioridad alta      1
5    David Ferrer  677665544         6.0  Candidato adecuado      2
6    Anna Paredes  633221144         4.5  Candidato adecuado      2
7  Anibal Paredes  644272727         4.5  Candidato adecuado      2
8    Sergio López  644112211        10.5      No prioritario      3
9      Marta Ruiz  699887766         9.0      No prioritario      3

-------------------------------------
Fin del informe.
-------------------------------------

# **Nivel 1**
## Ejercicio 2: Segmentación por riesgo de abandono del carrito

In [23]:
import pandas as pd

Añadimos la lista de clientes que necesitaremos para responder a las preguntas. Esta lista puede actualizarse cundo se requiera.

In [24]:
lista_clientes = [
    {"id_cliente": 1, "nombre": "Laura Serra", "edad": 23, "grupo_edad": "18-25", "codigo_comportamiento": 4},
    {"id_cliente": 2, "nombre": "Marc Vidal", "edad": 35, "grupo_edad": "26-40", "codigo_comportamiento": 3},
    {"id_cliente": 3, "nombre": "Ana López", "edad": 29, "grupo_edad": "26-40", "codigo_comportamiento": 2},
    {"id_cliente": 4, "nombre": "Joan Riera", "edad": 19, "grupo_edad": "18-25", "codigo_comportamiento": 2},
    {"id_cliente": 5, "nombre": "Mónica Pérez", "edad": 47, "grupo_edad": "41-60", "codigo_comportamiento": 4},
    {"id_cliente": 6, "nombre": "Luis García", "edad": 52, "grupo_edad": "41-60", "codigo_comportamiento": 1},
    {"id_cliente": 7, "nombre": "Pilar Sánchez", "edad": 61, "grupo_edad": "60+", "codigo_comportamiento": 3},
    {"id_cliente": 8, "nombre": "Eva Martín", "edad": 38, "grupo_edad": "26-40", "codigo_comportamiento": 0},
    {"id_cliente": 9, "nombre": "Diego Romero", "edad": 24, "grupo_edad": "18-25", "codigo_comportamiento": 1},
    {"id_cliente": 10, "nombre": "Núria Costa", "edad": 33, "grupo_edad": "26-40", "codigo_comportamiento": 4}
]

Creamos un diccionario con los códigos de comportamiento definidos por CRM

**» Códigos de comportamiento**

0 → Navega por la web pero no añade productos

1 → Añade productos pero no llega a la caja

2 → Llega a la caja pero no paga

3 → Cesta de la compra abandonada hace menos de 24 horas

4 → Cesta de la compra abandonada hace más de 24 horas

In [25]:
codigo_comportamiento = {
  "Navega por la web pero no añade productos" : 0,
  "Añade productos pero no llega a la caja" : 1,
  "Llega a la caja pero no paga" : 2,
  "Cesta de la compra abandonada hace menos de 24 horas" : 3,
  "Cesta de la compra abandonada hace más de 24 horas" : 4
}

Hacemos los mismo con el resto de informacion dada por el equipo de CRM

**» Factores por código de comportamiento**

Código 0 → 0,10

Código 1 → 0,25

Código 2 → 0,50

Código 3 → 0,75

Código 4 → 0,90

**» Factores por grupo de edad**

18–25 → 1,20

26–40 → 1,00

41–60 → 0,85

60+ → 0,70

In [26]:
# Diccionario 1: factores por codigo de comportamiento
factor_codigo = {
    0: 0.10,
    1: 0.25,
    2: 0.50,
    3: 0.75,
    4: 0.90
}

# Diccionario 2: factores por grupo de edad
factor_edad = {
    "18-25": 1.20,
    "26-40": 1.00,
    "41-60": 0.85,
    "60+":   0.70
}

Vamos a unificar en un mismo diccionario el **codigo de comportamiento**, el **segmento** del comprador, y los **mensajes** que serán dados por código para poder atraer a este tipo de clientes. Estos mensajes serán enviados por MRK para atraer la atencion del comprador.

In [27]:
tabla_comportamiento = {
    0 : {
     "segmento": "Sin intencion",
     "mensaje": "Descubre nuestras novedades y ofertas exclusivas para ti",
     "factor_codigo": 0.10},

    1 : {
     "segmento": "Explorador pasivo",
     "mensaje": "Los productos de tu lista estan disponibles. Anadelos al carrito!",
     "factor_codigo": 0.25},

    2 : {
     "segmento": "Casi comprador",
     "mensaje": "Tu pedido esta casi listo. Completa tu compra en 2 minutos",
     "factor_codigo": 0.50},

    3 : {
     "segmento": "Abandono reciente",
     "mensaje": "Tu cesta te espera! Tienes 24h para completar con envio gratis",
     "factor_codigo": 0.75},

    4 : {
     "segmento": "Abandono frio",
     "mensaje": "Recupera tu cesta con 10% de descuento exclusivo. Solo hoy",
     "factor_codigo": 0.90}
}

# DEFINIR LAS FUNCIONES que recibirá **procesar_clientes**

**FUNCIÓN** obtener_segmento_y_factor():

Nos devolverá el segmento, el mensaje y el factor_codigo de cada cliente.

Recibe un código de comportamiento (0-4) y retorna un diccionario con:

1. factor_codigo: peso numérico del comportamiento

2. segmento: nombre del segmento de marketing

3. mensaje: mensaje publicitario personalizado

In [28]:
def obtener_segmento_y_factor(codigo_comportamiento):
    return tabla_comportamiento[codigo_comportamiento]

**FUNCIÓN** obtener_factor_edad():

Nos devolverá el factor según el grupo de edad del cliente.

Recibe el grupo de edad del cliente y nos retorna el factor multiplicador correspondiente.

In [29]:
def obtener_factor_edad(grupo_edad):
    return factor_edad[grupo_edad]

**FUNCIÓN** calcular_riesgo():

Calcula el riesgo final teniendo el cuenta la *Fórmula de riesgo final*.

Fórmula de riesgo final:
**texto en negrita**
riesgo_final = factor_código * factor_edad.

In [30]:
def calcular_riesgo(factor_codigo, factor_edad):
    return round(factor_codigo * factor_edad, 3)

**FUNCIÓN** procesar_clientes():
1. Recibe la lista de nuestros clientes
2. Hacemos un bucle, analizará cada cliente del dicc de clientes.
3. De cada cliente, usaremos las funciones definidas antes: obtener segmento y factor, obtener factor edad y finalmente calcular su riesgo.
4. Una vez hecho esto, añadirá esta información como un diccionario a la lista creada en el paso 1.
5. Pedimos que nos devuelva un diccionario de diccionarios con segmento, mensaje, factores y riesgo_final.
.

In [31]:
def procesar_clientes(lista_clientes):

    clientes_procesados = {}

    for cliente in lista_clientes:
        id = cliente["id_cliente"]

        # Obtener datos de comportamiento (sin condicionales)
        info_comportamiento = obtener_segmento_y_factor(cliente["codigo_comportamiento"])
        factor_codigo = info_comportamiento["factor_codigo"]
        segmento = info_comportamiento["segmento"]
        mensaje = info_comportamiento["mensaje"]

        # Obtener factor de edad (sin condicionales)
        factor_edad = obtener_factor_edad(cliente["grupo_edad"])

        # Calcular riesgo final
        riesgo_final = calcular_riesgo(factor_codigo, factor_edad)

        # Construir registro completo
        clientes_procesados[id] = {
            "id_cliente": id,
            "nombre": cliente["nombre"],
            "edad": cliente["edad"],
            "grupo_edad": cliente["grupo_edad"],
            "codigo_comportamiento":cliente["codigo_comportamiento"],
            "segmento": segmento,
            "mensaje": mensaje,
            "factor_codigo": factor_codigo,
            "factor_edad": factor_edad,
            "riesgo_final": riesgo_final
        }

    return clientes_procesados

In [33]:
#comprobamos
procesar_clientes(lista_clientes)

{1: {'id_cliente': 1,
  'nombre': 'Laura Serra',
  'edad': 23,
  'grupo_edad': '18-25',
  'codigo_comportamiento': 4,
  'segmento': 'Abandono frio',
  'mensaje': 'Recupera tu cesta con 10% de descuento exclusivo. Solo hoy',
  'factor_codigo': 0.9,
  'factor_edad': 1.2,
  'riesgo_final': 1.08},
 2: {'id_cliente': 2,
  'nombre': 'Marc Vidal',
  'edad': 35,
  'grupo_edad': '26-40',
  'codigo_comportamiento': 3,
  'segmento': 'Abandono reciente',
  'mensaje': 'Tu cesta te espera! Tienes 24h para completar con envio gratis',
  'factor_codigo': 0.75,
  'factor_edad': 1.0,
  'riesgo_final': 0.75},
 3: {'id_cliente': 3,
  'nombre': 'Ana López',
  'edad': 29,
  'grupo_edad': '26-40',
  'codigo_comportamiento': 2,
  'segmento': 'Casi comprador',
  'mensaje': 'Tu pedido esta casi listo. Completa tu compra en 2 minutos',
  'factor_codigo': 0.5,
  'factor_edad': 1.0,
  'riesgo_final': 0.5},
 4: {'id_cliente': 4,
  'nombre': 'Joan Riera',
  'edad': 19,
  'grupo_edad': '18-25',
  'codigo_comportamiento': 2,
  'segmento': 'Casi comprador',
  'mensaje': 'Tu pedido esta casi listo. Completa tu compra en 2 minutos',
  'factor_codigo': 0.5,
  'factor_edad': 1.2,
  'riesgo_final': 0.6},
 5: {'id_cliente': 5,
  'nombre': 'Mónica Pérez',
  'edad': 47,
  'grupo_edad': '41-60',
  'codigo_comportamiento': 4,
  'segmento': 'Abandono frio',
  'mensaje': 'Recupera tu cesta con 10% de descuento exclusivo. Solo hoy',
  'factor_codigo': 0.9,
  'factor_edad': 0.85,
  'riesgo_final': 0.765},
 6: {'id_cliente': 6,
  'nombre': 'Luis García',
  'edad': 52,
  'grupo_edad': '41-60',
  'codigo_comportamiento': 1,
  'segmento': 'Explorador pasivo',
  'mensaje': 'Los productos de tu lista estan disponibles. Anadelos al carrito!',
  'factor_codigo': 0.25,
  'factor_edad': 0.85,
  'riesgo_final': 0.212},
 7: {'id_cliente': 7,
  'nombre': 'Pilar Sánchez',
  'edad': 61,
  'grupo_edad': '60+',
  'codigo_comportamiento': 3,
  'segmento': 'Abandono reciente',
  'mensaje': 'Tu cesta te espera! Tienes 24h para completar con envio gratis',
  'factor_codigo': 0.75,
  'factor_edad': 0.7,
  'riesgo_final': 0.525},
 8: {'id_cliente': 8,
  'nombre': 'Eva Martín',
  'edad': 38,
  'grupo_edad': '26-40',
  'codigo_comportamiento': 0,
  'segmento': 'Sin intencion',
  'mensaje': 'Descubre nuestras novedades y ofertas exclusivas para ti',
  'factor_codigo': 0.1,
  'factor_edad': 1.0,
  'riesgo_final': 0.1},
 9: {'id_cliente': 9,
  'nombre': 'Diego Romero',
  'edad': 24,
  'grupo_edad': '18-25',
  'codigo_comportamiento': 1,
  'segmento': 'Explorador pasivo',
  'mensaje': 'Los productos de tu lista estan disponibles. Anadelos al carrito!',
  'factor_codigo': 0.25,
  'factor_edad': 1.2,
  'riesgo_final': 0.3},
 10: {'id_cliente': 10,
  'nombre': 'Núria Costa',
  'edad': 33,
  'grupo_edad': '26-40',
  'codigo_comportamiento': 4,
  'segmento': 'Abandono frio',
  'mensaje': 'Recupera tu cesta con 10% de descuento exclusivo. Solo hoy',
  'factor_codigo': 0.9,
  'factor_edad': 1.0,
  'riesgo_final': 0.9}}

**FUNCIÓN** mostrar_dataframe():
1. Transformamos el diccionario anterior en un dataframe.
2. Ordenamos estos clientes por su "riesgo final" que hemos calculado.

In [34]:
def mostrar_dataframe(clientes_procesados):

    df_clientes_procesados = pd.DataFrame.from_dict(clientes_procesados, orient="index")
    df_ordenado = df_clientes_procesados.sort_values("riesgo_final", ascending=False)

    print("Listado de clientes actuales:")
    display(df_ordenado)

    return df_ordenado

**FUNCIÓN** mostrar_respuestas()
 1. Convertir a DataFrame para facilitar filtros
 2. Responder pregunta 1: clientes con riesgo alto, establecer un rango
 3. Responder pregunta 2: comparar clientes con mismo código pero distinta edad
 4. Responder pregunta 3: clientes con riesgo bajo, establecer un rango
 5. Responder pregunta 4: cliente con riesgo_final máximo

In [35]:
def mostrar_respuestas(clientes_procesados):

  df_clientes_procesados = pd.DataFrame.from_dict(clientes_procesados, orient="index")
  df_ordenado = df_clientes_procesados.sort_values("riesgo_final", ascending=False)

  # 1. ¿A qué clientes se debe contactar primero en una campaña de retargeting?

  print("\n")
  print("--------------------------------------------------------------------------")
  print("PREGUNTA 1 — ¿A qué clientes se debe contactar primero en retargeting?")
  print("--------------------------------------------------------------------------")

  # con el poco histórico y datos que tenemos, establezco un nivel de retargeting medio que puede ser cambiado según la cantidad de clientes o las prioridades de MKT.
  retargeting_level = 0.75
  df_retargeting = df_ordenado[df_ordenado["riesgo_final"] >= retargeting_level]

  display(df_retargeting)

  print("--------------------------------------------------------------------------")
  print(f"Tenemos {len(df_retargeting)} clientes presentan mayor potencial de recuperación.")


  # » 2. ¿Cuáles son las diferencias entre clientes con el mismo comportamiento pero de diferentes edades?
  print("\n")
  print("--------------------------------------------------------------------------")
  print("PREGUNTA 2 — ¿Cuáles son las diferencias entre clientes con el mismo comportamiento pero de diferentes edades?")
  print("--------------------------------------------------------------------------")


  # agrupamos por codigo de comportamiento y ordenamos por riesgo_final para tomar el maximo y el minimo y hacer la comparativa. Esto nos dará una comparativa medible.
  df_agrupado = df_ordenado.groupby("codigo_comportamiento")
  comportamiento_4 = df_agrupado.get_group(4)

  riesgo_max = comportamiento_4["riesgo_final"].max()
  riesgo_min = comportamiento_4["riesgo_final"].min()
  diferencia = round(riesgo_max - riesgo_min, 4)

  display(comportamiento_4)

  print("--------------------------------------------------------------------------")
  print(f"Diferencia de riesgo entre grupos de edad: {diferencia} %")


  # » 3. ¿Qué clientes muestran tan poco interés que no merece la pena invertir presupuesto en ellos?
  print("\n")
  print("--------------------------------------------------------------------------")
  print("PREGUNTA 3 — ¿Qué clientes muestran tan poco interés que no merece la pena invertir presupuesto en ellos?")
  print("--------------------------------------------------------------------------")

  # Establezco un umbral minimo para descartar estos clientes que puede ser cambiado según la cantidad de clientes o las prioridades de MKT.
  nivel_descarte = 0.25
  df_descarte = df_ordenado[df_ordenado["riesgo_final"] <= nivel_descarte]

  display(df_descarte)

  print("--------------------------------------------------------------------------")
  print(f"Tenemos {len(df_descarte)} clientes que no deben ser considerados para invertir presupuesto en ellos.")


  # » 4. ¿Qué cliente sería el más rentable recuperar?
  print("\n")
  print("--------------------------------------------------------------------------")
  print("PREGUNTA 4 — ¿Qué cliente sería el más rentable recuperar?")
  print("--------------------------------------------------------------------------")



  cliente_top = df_ordenado.loc[df_ordenado["riesgo_final"].idxmax()]

  print(f"Cliente más rentable de recuperar:")
  print(f"Nombre: {cliente_top['nombre']}")
  print(f"Edad: {cliente_top['edad']} años")

**FUNCIÓN** main_marketing()
1. Llamar a procesar_clientes
2. Llamar a mostrar_dataframe
3. Llamar a mostrar_respuestas

La lista de clientes se puede actualizar cuando el equipo de marketing quiera.

In [36]:
def main_marketing():

    # Paso 1: Procesar todos los clientes
    clientes_procesados = procesar_clientes(lista_clientes)

    # Paso 2: Mostrar tabla completa
    mostrar_dataframe(clientes_procesados)

    # Paso 3: Mostrar respuestas a la preguntas de MKT.
    mostrar_respuestas(clientes_procesados)

In [37]:
#COMPROBAMOS PROGRAMA FINAL
main_marketing()

Listado de clientes actuales:

,id_cliente,nombre,edad,grupo_edad,codigo_comportamiento,segmento,mensaje,factor_codigo,factor_edad,riesgo_final
1,1,Laura Serra,23,18-25,4,Abandono frio,Recupera tu cesta con 10% de descuento exclusi...,0.90,1.20,1.080
10,10,Núria Costa,33,26-40,4,Abandono frio,Recupera tu cesta con 10% de descuento exclusi...,0.90,1.00,0.900
5,5,Mónica Pérez,47,41-60,4,Abandono frio,Recupera tu cesta con 10% de descuento exclusi...,0.90,0.85,0.765
2,2,Marc Vidal,35,26-40,3,Abandono reciente,Tu cesta te espera! Tienes 24h para completar ...,0.75,1.00,0.750
4,4,Joan Riera,19,18-25,2,Casi comprador,Tu pedido esta casi listo. Completa tu compra ...,0.50,1.20,0.600
7,7,Pilar Sánchez,61,60+,3,Abandono reciente,Tu cesta te espera! Tienes 24h para completar ...,0.75,0.70,0.525
3,3,Ana López,29,26-40,2,Casi comprador,Tu pedido esta casi listo. Completa tu compra ...,0.50,1.00,0.500
9,9,Diego Romero,24,18-25,1,Explorador pasivo,Los productos de tu lista estan disponibles. A...,0.25,1.20,0.300
6,6,Luis García,52,41-60,1,Explorador pasivo,Los productos de tu lista estan disponibles. A...,0.25,0.85,0.212
8,8,Eva Martín,38,26-40,0,Sin intencion,Descubre nuestras novedades y ofertas exclusiv...,0.10,1.00,0.100

--------------------------------------------------------------------------
PREGUNTA 1 — ¿A qué clientes se debe contactar primero en retargeting?
--------------------------------------------------------------------------

,id_cliente,nombre,edad,grupo_edad,codigo_comportamiento,segmento,mensaje,factor_codigo,factor_edad,riesgo_final
1,1,Laura Serra,23,18-25,4,Abandono frio,Recupera tu cesta con 10% de descuento exclusi...,0.90,1.20,1.080
10,10,Núria Costa,33,26-40,4,Abandono frio,Recupera tu cesta con 10% de descuento exclusi...,0.90,1.00,0.900
5,5,Mónica Pérez,47,41-60,4,Abandono frio,Recupera tu cesta con 10% de descuento exclusi...,0.90,0.85,0.765
2,2,Marc Vidal,35,26-40,3,Abandono reciente,Tu cesta te espera! Tienes 24h para completar ...,0.75,1.00,0.750

--------------------------------------------------------------------------
Tenemos 4 clientes presentan mayor potencial de recuperación.


--------------------------------------------------------------------------
PREGUNTA 2 — ¿Cuáles son las diferencias entre clientes con el mismo comportamiento pero de diferentes edades?
--------------------------------------------------------------------------

,id_cliente,nombre,edad,grupo_edad,codigo_comportamiento,segmento,mensaje,factor_codigo,factor_edad,riesgo_final
1,1,Laura Serra,23,18-25,4,Abandono frio,Recupera tu cesta con 10% de descuento exclusi...,0.9,1.20,1.080
10,10,Núria Costa,33,26-40,4,Abandono frio,Recupera tu cesta con 10% de descuento exclusi...,0.9,1.00,0.900
5,5,Mónica Pérez,47,41-60,4,Abandono frio,Recupera tu cesta con 10% de descuento exclusi...,0.9,0.85,0.765

--------------------------------------------------------------------------
Diferencia de riesgo entre grupos de edad: 0.315 %


--------------------------------------------------------------------------
PREGUNTA 3 — ¿Qué clientes muestran tan poco interés que no merece la pena invertir presupuesto en ellos?
--------------------------------------------------------------------------

,id_cliente,nombre,edad,grupo_edad,codigo_comportamiento,segmento,mensaje,factor_codigo,factor_edad,riesgo_final
6,6,Luis García,52,41-60,1,Explorador pasivo,Los productos de tu lista estan disponibles. A...,0.25,0.85,0.212
8,8,Eva Martín,38,26-40,0,Sin intencion,Descubre nuestras novedades y ofertas exclusiv...,0.10,1.00,0.100

--------------------------------------------------------------------------
Tenemos 2 clientes que no deben ser considerados para invertir presupuesto en ellos.


--------------------------------------------------------------------------
PREGUNTA 4 — ¿Qué cliente sería el más rentable recuperar?
--------------------------------------------------------------------------
Cliente más rentable de recuperar:
Nombre: Laura Serra
Edad: 23 años

# **Nivel 2**
## Ejercicio 1: Gestión de riesgos y priorización de pacientes

Introducimos los datos de los pacientes que proceden del sistema, estos datos podrán ser actualizados cuando sea necesario.

In [38]:
pacientes = [
    "Maria|45|tos, Fiebre Alta, dolor_pecho",
    "Luis|33|dolor_cabeza,faTiga",
    "Sara|67|fiebre alta, dificultad RESPIRAR, tos",
    "Jordi|52|fatiga , tos",
    "Anna|29|fiebre alta,dolor_cabeza"
]

Cargamos los datos de niveles de riesgo que el departamento médico nos ha facilitado.

In [39]:
niveles_riesgo = {
    "fiebre_alta": 3,
    "dificultad_respirar": 5,
    "dolor_pecho": 4,
    "tos": 1,
    "fatiga": 1,
    "dolor_cabeza": 1
}

Establezco los pasos a seguir y las funciones que utilizaré para obtener el dataframe que los médicos han pedido:

1. **FUNCIÓN *split_datos*:** Separamos los datos de la lista pacientes (separar correctamente con comas).
2. **FUNCIÓN *limpiar_datos*:** Poner en minúsculas y eliminar espacios.
3. **FUNCIÓN *desglosar_pacientes*:** crear un diccionario de cada paciente.
4. **FUNCIÓN *calcular_riesgo*:** sumar todos los nieveles de riesgo de cada sintoma de cada paciente.
5. **FUNCION *procesar_pacientes*:** utilizamos las funciones anteriores para crear un diccionario completo
6. **FUNCION *dataframe_pacientes*:** convertimos el diccionario en un dataframe
7. **FUNCIÓN *ordenar_pacientes*:** ordenamos por el riesgo que hemos calculado en la función anterior.
8. **FUNCIÓN *main_pacientes*:** llama todas las funciones anteriores y te devuelve e imprime un dataframe de todos los pacientes ordenamos de riesgo mayor a riesgo menor.

**FUNCIÓN** split_datos():
Nos devolverá la lista de pacientes en un diccionario con cada uno de ellos separados.
1. Dividir la lista por ","
2. Crear un diccionario con cada paciente
3. Convertir el diccionario en un dataframe para que sea mas facil visualizar y separar datos.

In [40]:
def split_datos(pacientes):
    lista_pacientes = []
    for p in pacientes:
        partes = p.split("|")
        lista_pacientes.append({
            "nombre":   partes[0].strip(),
            "edad":     int(partes[1].strip()),
            "sintomas": partes[2].strip()
        })
    return lista_pacientes

**FUNCIÓN** limpiar_datos:

Recibe el diccionario de pacientes.
1. Separar los sintomas por las comas.
2. Limpiar los sintomas: no espacios delante o detrás, pasar a minusculas y cambiar espacios por "_".
3. Generar un nuevo diccioanrio con estos datos limpios.

In [41]:
def limpiar_datos(lista):
  lista_pacientes = split_datos(pacientes)
  #necesito recorrer la lista de diccionarios hasta que encuentre "sintomas" y aplique la limpieza

  for paciente in lista_pacientes:
    sintomas_limpios = [
    sintoma.strip().lower().replace(" ", "_")     # .strip: quitar espacios del principio y del final
                                          # .replace: reemplazar los espacios internos por "_" y TODO a minusculas
      for sintoma in paciente['sintomas'].split(',') # .split: separar por las comas para crear una lista
      ]


    paciente['sintomas'] = sintomas_limpios #reemplazamos "sintomas" por la nueva lista de sintomas limpia
  return lista_pacientes

**FUNCIÓN** desglosar_pacientes():

Necesito que me devuelva un diccionario por paciente usando el nombre como clave para después buscar mejor los sintomas.

In [42]:
def desglosar_pacientes(lista_pacientes):
  pacientes_desglosados = {}

  # Recorrer la lista y asignar cada diccionario usando el nombre como clave
  for paciente in lista_pacientes:
      nombre = paciente["nombre"]
      pacientes_desglosados[nombre] = paciente

  return pacientes_desglosados

**FUNCIÓN** calcular_riesgo:
1. Sumar todos los niveles de riesgo de cada sintoma de cada paciente.

In [43]:
def calcular_riesgo(paciente, niveles_riesgo):
    suma_riesgo = 0
  # Recorrer cada paciente en la lista

    for sintoma in paciente["sintomas"]:
        suma_riesgo += niveles_riesgo.get(sintoma, 0)
    return suma_riesgo

**FUNCIÓN** procesar_pacientes():
Todas las funciones anteriores juntas para transformar en un dataframe.
1. split_datos
2. limpiar_datos
3. calcular_riesgo

In [44]:
def procesar_pacientes(pacientes, niveles_riesgo):

    lista_pacientes = split_datos(pacientes)

    lista_limpia = limpiar_datos(lista_pacientes)

    pacientes_desglosados = desglosar_pacientes(lista_limpia)  # dict {nombre: paciente}

    lista_final = []

    for nombre, paciente in pacientes_desglosados.items():
        riesgo_total = calcular_riesgo(paciente, niveles_riesgo)  # paciente por paciente
        lista_final.append({
            "nombre": paciente["nombre"],
            "edad": paciente["edad"],
            "sintomas": paciente["sintomas"],
            "riesgo_total": riesgo_total
        })

    return lista_final

In [46]:
#comproba que funciona
procesar_pacientes(pacientes, niveles_riesgo)

[{'nombre': 'Maria',
  'edad': 45,
  'sintomas': ['tos', 'fiebre_alta', 'dolor_pecho'],
  'riesgo_total': 8},
 {'nombre': 'Luis',
  'edad': 33,
  'sintomas': ['dolor_cabeza', 'fatiga'],
  'riesgo_total': 2},
 {'nombre': 'Sara',
  'edad': 67,
  'sintomas': ['fiebre_alta', 'dificultad_respirar', 'tos'],
  'riesgo_total': 9},
 {'nombre': 'Jordi',
  'edad': 52,
  'sintomas': ['fatiga', 'tos'],
  'riesgo_total': 2},
 {'nombre': 'Anna',
  'edad': 29,
  'sintomas': ['fiebre_alta', 'dolor_cabeza'],
  'riesgo_total': 4}]

**FUNCION** dataframe_pacientes:

Convertimos el diccionario en un dataframe

In [47]:
def dataframe_pacientes(lista):
  df_pacientes = pd.DataFrame(lista)
  return df_pacientes

**FUNCIÓN** ordenar_pacientes:

Ordenamos el dataframe final de los pacientes de mayor a menor teniendo como medida la columna de riesgo calculado.

In [45]:
def ordenar_pacientes(df):
  df_ordenado = df.sort_values(["riesgo_total", "edad"], ascending=[False, False]) #ordeno también por edad por si hay empates (en este caso lo hay)
  return df_ordenado

**FUNCIÓN** main_pacientes():
1. Llamar a la función procesar_pacientes que a su vez está compuesta por las funciones ya definidas.
2. Llamar a la función dataframe_pacientes.
3. Llamar a la función df_ordenado
4. Que retorne el dataframe ordenado
5. Visualizar el orden de atención de los pacientes para los médicos.

In [ ]:
def main_pacientes(pacientes, niveles_riesgo):

  lista_final = procesar_pacientes(pacientes, niveles_riesgo)
  df_ok = dataframe_pacientes(lista_final)
  df_final = ordenar_pacientes(df_ok)

  print("-----------------------------------------")
  print("   ORDEN DE ATENCIÓN DE LOS PACIENTES")
  print("-----------------------------------------")
  for i, nombre in enumerate(df_final["nombre"], start=1): # sin start, empieza desde 0, queda raro
    print(f"{i}. {nombre}")
  print("")

  return df_final

Finalmente, llamamos a la función ppal para ver si funciona:

In [ ]:
main_pacientes(pacientes, niveles_riesgo)

-----------------------------------------
   ORDEN DE ATENCIÓN DE LOS PACIENTES
-----------------------------------------
1. Sara
2. Maria
3. Anna
4. Jordi
5. Luis

  nombre  edad                                 sintomas  riesgo_total
2   Sara    67  [fiebre_alta, dificultad_respirar, tos]             9
0  Maria    45          [tos, fiebre_alta, dolor_pecho]             8
4   Anna    29              [fiebre_alta, dolor_cabeza]             4
3  Jordi    52                            [fatiga, tos]             2
1   Luis    33                   [dolor_cabeza, fatiga]             2

# **Nivel 2**
## Ejercicio 2: Clasificación de clientes de seguros

Introducimos los datos de los clientes que la empresa nos ha dado, esta lista puede ser actualizada cuando sea necesario.

In [ ]:
clientes = [
    {"nombre": "Ana", "edad": 42, "código": 0},
    {"nombre": "Carlos", "edad": 30, "código": 2},
    {"nombre": "Isabel", "edad": 55, "código": 3},
    {"nombre": "Jorge", "edad": 40, "código": 1},
    {"nombre": "Marta", "edad": 28, "código": 0},
]

Introducimos la categoría de niveles establecida por la empresa.

In [ ]:
niveles_seguro = {
    0: {"categoría": "Riesgo bajo", "precio_base": 120, "fraude": 0.01},
    1: {"categoría": "Riesgo medio", "precio_base": 200, "fraude": 0.05},
    2: {"categoría": "Riesgo alto", "precio_base": 350, "fraude": 0.15},
    3: {"categoría": "Riesgo crítico", "precio_base": 500, "fraude": 0.30},
}

Establezco los pasos a seguir y las funciones que utilizaré para obtener el dataframe  y el análisis que la empresa me ha pedido:

1. **FUNCIÓN *convertir_lista*:** Convertimos la lsita de clientes en un dataframe, una tabla con una visualización más fácil.
2. **FUNCIÓN *convertir_diccionario*:** Convertimos el diccionario de los niveles que ha establecido el seguro en un dataframe, una tabla con una visualización más fácil.
3. **FUNCIÓN *combinar_df*:** Combinamos ambas tablas en una sola, siempre el nivel del seguro coincida con el código del cliente.
4. **FUNCIÓN *eliminar_col*:** eliminamos las columnas innecesarias para la empresa, las que no nos han pedido, como "*código*" y "*nivel*".
5. **FUNCION *calcular_precio_final*:** Creamos y añadimos a la tabla una columna calculada con la fórmula dada por la compañia.
6. **FUNCION *ordeanr_dataframe*:** Ordenamos la tabla por precio final y por el riesgo de fraude en orden descendente.
7. **FUNCIÓN *respuestas_analisis*:** Respondemos a las preguntas que nos han dado y las mostramos.
8. **FUNCIÓN *main_seguros*:** llama todas las funciones anteriores. Te muestra el análisis pedido y te devuelve un tabla ordenada con los clientes del seguro.

**FUNCIÓN** convertir_lista():
1. Pedir como variable la lista de clientes.
2. Convertir la lista en un dataframe.
3. Devuelve el dataframe

In [ ]:
def convertir_lista(lista):
  df_clientes = pd.DataFrame(lista)
  return df_clientes

**FUNCIÓN** convertir_diccionario():
1. Pedir como variable el diccionario con los niveles del seguro.
2. Convertir el diccionario en un dataframe.
3. Convertir el indice en una columna, como el número de los niveles.
4. Devuelve el dataframe

In [ ]:
def convertir_diccionario(diccionario):
  df = pd.DataFrame.from_dict(diccionario, orient='index')
  df_niveles = df.reset_index().rename(columns={'index': 'nivel'})
  return df_niveles

**FUNCIÓN** combinar_df():
1. Pedir como variables los 2 dataframes creados en las funciones 1 y 2.
2. Combinar ambas tablas donde coincidan el *código* con el *nivel*.
3. Tomar como referencia la tabla de clientes.
4. Devuelve el dataframe combinado.

In [ ]:
def combinar_df (df1, df2):
  df_combinado = df1.merge(df2, left_on='código', right_on='nivel', how='inner')
  return df_combinado

**FUNCIÓN** eliminar_col():
1. Pedir como variable el dataframe combinado de la función anterior.
2. Eliminar las columnas de *código* y *nivel* que la compañia no nos ha pedido.
3. Devuelve el dataframe.

In [ ]:
def eliminar_col(df):
  df_final = df.drop(columns=["código", "nivel"])
  return df_final

**FUNCIÓN** calcular_precio_final():
1. Pedir como variable el dataframe de la función anterior.
2. Crear una columna calculado y añadirla a la tabla.

**Fórmula**: precio_final = precio_base * (1 + edad/100)

3. Devuelve el dataframe final con las columnas definitivas.

In [ ]:
def calcular_precio_final(df):
  # Crear columna calculada 'precio final'
  df["precio_final"] = df["precio_base"] * (1 + df["edad"] / 100)
  return df

**FUNCIÓN** ordenar_df():
1. Pedir como variable el dataframe final.
2. Ordenar por el precio final y por *probabilidad de fraude.
3. Devuelve el dataframe ordenado.

In [ ]:
def ordenar_df(df):
  # Ordenar por precio_final y fraude de forma descendente
  df_ordenado = df.sort_values(by=['precio_final', 'fraude'], ascending=False)
  return df_ordenado

**FUNCIÓN** respuestas_analisis():
1. Pedir como variable el dataframe final ordenado.
2. Pregunta 1: el cliente con el nivel de fraude más alto. Mostramos su nombre.  
3. Pregunta 2: El cliente que tiene un precio del seguro más alto. Mostramos su nombre.
4. Pregunta 3: Hay varios clientes que debería ser revisado anualmente. Establecemos un rango, en este caso los que están en el tramo *Riesgo Alto* y *Riesgo crítico*. Mostramos sus nombres, pueden ser varios.

In [ ]:
def respuestas_analisis(df):

  # 1. ¿qué cliente tiene mas probabilidad de fraude?
  cliente_top_fraude = df.loc[df['fraude'].idxmax(), 'nombre']
  print("------------------  ANÁLISIS DEL SEGURO ----------------------\n")
  print(f"- Cliente con más probabilidad de fraude: {cliente_top_fraude}\n")

  # 2. ¿Cuál tiene el precio final más alto?
  cliente_top_precio = df.loc[df['precio_final'].idxmax(), "nombre"]
  print(f"- Cliente con el precio final más alto: {cliente_top_precio} \n")

  # 3. ¿Quién sería prioritario para una revisión manual?
  # Filtrar clientes con fraude mayor o igual a 0.15 (15%) RIESGO ALTO Y CRITICO
  prioritarios = df[df['fraude'] >= 0.15]
  nombres_juntos = ", ".join(prioritarios['nombre'])
  print(f"- Clientes prioritarios para revisión manual: {nombres_juntos}\n")

  print("--------------------------------------------------------------\n")

**FUNCIÓN** main_seguros():
1. Pedir como variable la lista inicial de clientes y el diccionario de niveles.
2. Llamamos una por una a las funciones anteriores hasta obtener el dataframe final ordenado.
3. Mostramos las respuestas al análisis solicitado.
4. Devuelve la tabla de clientes final ordenada.

In [ ]:
def main_seguros(lista, diccionario):

  df_clientes = convertir_lista(lista)

  df_niveles = convertir_diccionario(diccionario)

  df_combinado = combinar_df (df_clientes, df_niveles)

  df_final = eliminar_col(df_combinado)

  df_completo = calcular_precio_final(df_final)

  df_ordenado = ordenar_df(df_completo)

  analisis = respuestas_analisis(df_ordenado)

  return df_ordenado

Comprobamos y ejecutamos el programa.

In [ ]:
main_seguros(clientes, niveles_seguro)

------------------  ANÁLISIS DEL SEGURO ----------------------

- Cliente con más probabilidad de fraude: Isabel

- Cliente con el precio final más alto: Isabel

- Clientes prioritarios para revisión manual: Isabel, Carlos

--------------------------------------------------------------

   nombre  edad       categoría  precio_base  fraude  precio_final
2  Isabel    55  Riesgo crítico          500    0.30         775.0
1  Carlos    30     Riesgo alto          350    0.15         455.0
3   Jorge    40    Riesgo medio          200    0.05         280.0
0     Ana    42     Riesgo bajo          120    0.01         170.4
4   Marta    28     Riesgo bajo          120    0.01         153.6

# **Nivel 3**
## Ejercicio 1: Generador de contraseñas seguras

1. Vamos a importar "*secrets*" que está diseñada para generar números y datos aleatorios criptográficamente seguros. Podríamos importar "*random*" pero la contraseña no sería tan segura.

2. Importamos la biblioteca numpy para poder obtener listas de números, letras y símbolos sin necesidad de escribirlas manualmente.

In [ ]:
import secrets
import numpy as np

Definimos las listas con los caracteres que necesitaremos para poder comprobar que nuestras funciones devuelven resultados correctos.

In [ ]:
lista_mayusculas = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"]

lista_minusculas = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]

lista_numeros = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]

lista_signos = ["*", "!", "@", "#", "$", ".", "%"]

Establezco los pasos a seguir y las funciones que utilizaré para poder generar la contraseña segura tal y como nos piden:

1. **FUNCIÓN *obtener_longitud*:** Necesitamos una longitud segura para la contraseña. De no ser segura, devuelve un error.
2. **FUNCIÓN *obtener_mayusculas*:** Conseguir una lista de mayúsculas desde la biblioteca numpy.
3. **FUNCIÓN *obtener_minusculas*:** Conseguir una lista de minúsculas desde la biblioteca numpy.
4. **FUNCIÓN *obtener_numeros*:** Conseguir una lista de números desde la biblioteca numpy.
5. **FUNCION *obtener_signos*:** Conseguir una lista de símbolos desde la biblioteca numpy.
6. **FUNCION *obtener_random*:** Conseguir que combine aleatoriamente y de forma segura una lista de caracteres.
7. **FUNCIÓN *crear_contraseña*:** Combina todas las funciones anteriores en una sola y devuelve la contraseña generada.

**FUNCIÓN** obtener_longitud():
1. Determinamos un rango de longitud estándar y segura que pueda contener varios tipos de caracteres para la contraseña
2. Si es demasiado corta, no será segura.
3. Si es demasiado larga será dificil de recordar.
4. Devuelve la longitud cuando esté dentro del rango correcto.

In [ ]:
def definir_longitud(num):
  longitud = int(num)

  if longitud >= 8 and longitud <= 12:
    return longitud
  else:
    print("ERROR. La longitud de la contraseña debe estar entre 8 y 12 caracteres.")

In [ ]:
#comprobamos
print(definir_longitud(8))

#comprobamos error
definir_longitud(2)

8
ERROR. La longitud de la contraseña debe estar entre 8 y 12 caracteres.

**FUNCIÓN** obtener_mayusculas():
1. Utilizamos la biblioteca numpy, tal y como nos recomienda el ejercicio. De no ser asi, escribiríamos todas las letras del abecedario de manera manual.
2.  Utilizamos el **Código ASCII**, que asigna un número único a cada carácter (letra del abecedario en mayúsculas) del 65 al 91.
3. Creamos una lista de mayúsculas vacia.
4. Con un bucle recorremos cada caracter del código ASCII y lo añadimos a la lista que teniamos vacia.
5. Devuelve una lista de letras de la A a la Z.

In [ ]:
def obtener_mayusculas():
  mayusculas = []  # Creamos la lista de mayúsculas vacía

  for i in range(65, 91):  # Recorremos del 65 al 91
      letra = chr(i)       # Convertimos el número a letra según el código ASCII
      mayusculas.append(letra)  # Agragamos cada letra a la lista vacia

  return mayusculas

In [ ]:
#comprobamos
obtener_mayusculas()

['A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z']

**FUNCIÓN** obtener_minusculas():
1. Utilizamos la biblioteca numpy, tal y como nos recomienda el ejercicio. De no ser asi, escribiríamos todas las letras del abecedario de manera manual.
2.  Utilizamos el **Código ASCII**, que asigna un número único a cada carácter (letra del abecedario en **minúsculas**) del 97 al 123.
3. Creamos una lista de minúsculas vacia.
4. Con un bucle recorremos cada caracter del código ASCII y lo añadimos a la lista que teniamos vacia.
5. Devuelve una lista de letras de la *"a"* a la *"z"*.

In [ ]:
def obtener_minusculas():
  minusculas = []  # Creamos la lista de minúsculas vacía

  for i in range(97, 123):  # Recorremos del 97 al 123
      letra = chr(i)       # Convertimos el número a letra según el código ASCII
      minusculas.append(letra)  # Agragamos cada letra a la lista vacia

  return minusculas

In [ ]:
# comprobamos
obtener_minusculas()

['a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z']

**FUNCIÓN** obtener_numeros():
1. Utilizamos la biblioteca numpy, tal y como nos recomienda el ejercicio. De no ser asi, escribiríamos todas las letras del abecedario de manera manual.
2.  Utilizamos el **Código ASCII** del 48 al 58.
3. Creamos una lista de números vacia.
4. Con un bucle recorremos cada caracter del código ASCII y lo añadimos a la lista que teniamos vacia.
5. Devuelve una lista de números del *"0"* al *"9"*.

In [ ]:
def obtener_numeros():
  numeros = []  # Creamos la lista de números vacia

  for i in range(48, 58):  # Recorremos del 48 al 58
      numero = chr(i)       # Convertimos el número a letra según el código ASCII
      numeros.append(numero)  # Agragamos cada letra a la lista vacia

  return numeros

In [ ]:
# comprobamos
obtener_numeros()

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

**FUNCIÓN** obtener_signos():
1. Creamos una lista con los símbolo que queramos aplicar a nuestra contraseña. Esta lista puede apliarse o limitarse según sea necesario.
2. Devolvemos y guardamos esta lista.

*No he utilizado el código ASCII en este caso porque lo números del codigo asociado a caracteres especiales son muy dispersos y creo que es más eficaz si nosotros elegimos los símbolos que queremos.*

In [ ]:
def obtener_signos():
  signos = ["*", "!", "@", "#", "$", ".", "%", "&", "@"]
  return signos

In [ ]:
# comprobamos
obtener_signos()

['*', '!', '@', '#', '$', '.', '%', '&', '@']

**FUNCIÓN** obtener_signos():
1. Pedimos 4 variables que obtenemos de las 4 funciones anteriores.
2. Creamos una variable cuyo valor es la combinación las 4 variables anteriores.
3. Creamos una lista vacia para neustra contraseña.
4. Generamos un buble que se repetirá el número de veces que nos marqué el usuario como longitud de la contraseña.
5. El bucle recorré todos los caracteres definidos de manera aleatoria y los añade a la lista.
6. Unimos la lista de caracteres en un string con "".join().
7. Devuelve la lista en forma de string.

In [ ]:
def obtener_random(var1, var2, var3, var4, longitud):
  caracteres = var1 + var2 + var3 + var4

  contraseña = []

  for i in range(longitud):
    caracteres_random = secrets.choice(caracteres)
    contraseña.append(caracteres_random)
    contraseña_final = "".join(contraseña)
  return contraseña_final

In [ ]:
#comprobamos
obtener_random(lista_mayusculas, lista_minusculas, lista_numeros, lista_signos, 12)

'vGaWBRSJ!r8x'

**FUNCIÓN** crear contraseña():
1. Llamamos una por una a las funciones creadas anteriormente asignándolas a una variable.
2. Imprimimos la contraseña para que el usuario pueda verla y memorizarla o guardarla.
3. Devolvemos la contraseña.

In [ ]:
def crear_contraseña(num, mayusculas=True, minusculas=True, numeros=True, signos=False):

  longitud = definir_longitud(num)

  mayusculas = obtener_mayusculas()
  minusculas = obtener_minusculas()
  numeros = obtener_numeros()
  signos = obtener_signos()

  contraseña_final = obtener_random(mayusculas, minusculas, numeros, signos, longitud)

  print(f"Tu nueva contraseña generada es: {contraseña_final} \n")
  return contraseña_final

In [ ]:
#comprobamos

crear_contraseña(12, mayusculas=True, minusculas=True, numeros=True, signos=False)

Tu nueva contraseña generada es: Wom15dE&rDz9

'Wom15dE&rDz9'

In [ ]:
#comprobamos para ver si nos devuelve otra contraseña
crear_contraseña(8, mayusculas=True, minusculas=True, numeros=True, signos=False)

Tu nueva contraseña generada es: ZA7Y2#Pi

'ZA7Y2#Pi'

# **Nivel 3**
## Ejercicio 2: Procesamiento automatizado de datos deportivos

Establezco los pasos a seguir y las funciones que utilizaré para poder devolver los resultados automatizados que nos piden:

1. **FUNCIÓN *subir_historico*:** Necesitamos subir un archivo para que podamos obtener los datos actualizados.
2. **FUNCIÓN *historico_dataframe*:** Convertimos el archivo.txt subido en un dataframe de fácil lectura y visualización.
3. **FUNCIÓN *calcular_puntos*:**
Un dataframe con los puntos obtenidos por cada equipo teniendo en cuenta el resultado de los partidos.
4. **FUNCIÓN *calcular_goles*:** Sumamos los goles en contra y a favor de cada equipo.
5. **FUNCION *combinar_resultados*:** Unimos todas las tablas anteriores en un sola tal y cómo nos han pedido.
6. **FUNCION *respuestas_clasificación*:** Mostrar los resultados que nos han pedido.
7. **FUNCIÓN *main_partidos*:** Combina todas las funciones anteriores en una sola y devuelve el dataframe generado.

In [ ]:
import pandas as pd
import numpy as np

**FUNCIÓN** *subir_historico*:
1. Código para desplegar un botón para cargar datasets.
2. Subimos el archivo
3. Devuelve y gaurda el archivo subido.

In [ ]:
def subir_historico():
  from google.colab import files

  #subir archivo
  subido = files.upload()

  return subido

In [ ]:
#comprobamos
subir_historico()

Saving historic_partits.txt to historic_partits.txt

{'historic_partits.txt': b'Manlleu\t0-1\tGranollers\nVilafranca\t4-5\tTerrassa\nOlot\t5-0\tGranollers\nVilafranca\t5-5\tManlleu\nCornell\xc3\xa0\t5-1\tPrat\nCerdanyola\t0-5\tVilafranca\nSant Andreu\t2-3\tCornell\xc3\xa0\nVilafranca\t5-4\tOlot\nFC Barcelona\t4-4\tBadalona\nGranollers\t1-5\tSabadell\nGranollers\t0-5\tEuropa\nPrat\t5-2\tLlagostera\nLlagostera\t2-5\tVilafranca\nSant Andreu\t1-4\tFigueres\nFigueres\t1-2\tCerdanyola\nGranollers\t0-4\tCornell\xc3\xa0\nFigueres\t2-3\tRCD Espanyol\nLlagostera\t2-5\tFigueres\nCornell\xc3\xa0\t3-1\tReus Deportiu\nEuropa\t5-1\tGranollers\nTerrassa\t0-4\tEuropa\nOlot\t1-2\tSant Andreu\nVilafranca\t5-2\tEuropa\nVilafranca\t1-5\tReus Deportiu\nReus Deportiu\t4-4\tN\xc3\xa0stic de Tarragona\nPrat\t3-0\tLleida Esportiu\nSant Andreu\t1-2\tCerdanyola\nGranollers\t2-0\tPrat\nVilafranca\t5-5\tTerrassa\nGirona FC\t3-0\tN\xc3\xa0stic de Tarragona\nCerdanyola\t2-4\tOlot\nPrat\t3-2\tN\xc3\xa0stic de Tarragona\nFigueres\t4-4\tTerrassa\nBadalona\t4-3\tSant Andreu\nBadalona\t3-4\tManlleu\nTerrassa\t4-0\tN\xc3\xa0stic de Tarragona\nReus Deportiu\t1-0\tLlagostera\nManlleu\t2-3\tBadalona\nGranollers\t2-3\tN\xc3\xa0stic de Tarragona\nFigueres\t4-1\tLleida Esportiu\nOlot\t1-1\tFC Barcelona\nManlleu\t2-5\tGirona FC\nFigueres\t5-5\tCornell\xc3\xa0\nLlagostera\t3-1\tFigueres\nCerdanyola\t5-1\tManlleu\nOlot\t4-0\tFC Barcelona\nBadalona\t4-2\tFC Barcelona\nSabadell\t5-1\tLleida Esportiu\nGirona FC\t0-3\tRCD Espanyol\nTerrassa\t0-4\tGirona FC\nManlleu\t2-1\tN\xc3\xa0stic de Tarragona\nFC Barcelona\t5-2\tTerrassa\nFC Barcelona\t5-3\tRCD Espanyol\nLleida Esportiu\t0-2\tSabadell\nVilafranca\t4-2\tBadalona\nTerrassa\t1-2\tCornell\xc3\xa0\nSabadell\t3-2\tOlot\nFigueres\t2-5\tGranollers\nVilafranca\t1-2\tRCD Espanyol\nCerdanyola\t0-0\tManlleu\nVilafranca\t3-4\tLleida Esportiu\nVilafranca\t4-0\tCerdanyola\nOlot\t2-3\tBadalona\nPrat\t5-4\tEuropa\nCerdanyola\t4-5\tLleida Esportiu\nSant Andreu\t0-2\tGirona FC\nCornell\xc3\xa0\t5-5\tTerrassa\nGranollers\t5-2\tVilafranca\nSant Andreu\t5-5\tVilafranca\nLlagostera\t5-4\tRCD Espanyol\nBadalona\t0-3\tSabadell\nOlot\t3-0\tRCD Espanyol\nPrat\t5-2\tCerdanyola\nCornell\xc3\xa0\t3-5\tManlleu\nCornell\xc3\xa0\t0-3\tLleida Esportiu\nBadalona\t5-4\tLleida Esportiu\nLlagostera\t2-0\tTerrassa\nBadalona\t3-3\tEuropa\nLlagostera\t0-4\tEuropa\nVilafranca\t4-0\tPrat\nCerdanyola\t5-3\tVilafranca\nGirona FC\t3-4\tLleida Esportiu\nGirona FC\t1-0\tLlagostera\nCerdanyola\t4-1\tGirona FC\nLleida Esportiu\t2-3\tReus Deportiu\nN\xc3\xa0stic de Tarragona\t3-4\tOlot\nPrat\t1-0\tFigueres\nFigueres\t4-0\tCerdanyola\nGirona FC\t5-1\tOlot\nLlagostera\t3-0\tVilafranca\nEuropa\t2-0\tSant Andreu\nFigueres\t1-5\tReus Deportiu\nSant Andreu\t2-2\tLleida Esportiu\nOlot\t4-4\tCerdanyola\nCornell\xc3\xa0\t2-5\tLleida Esportiu\nTerrassa\t4-5\tGranollers\nVilafranca\t0-0\tN\xc3\xa0stic de Tarragona\nCornell\xc3\xa0\t2-5\tFC Barcelona\nManlleu\t5-2\tGirona FC\nManlleu\t2-1\tSant Andreu\nRCD Espanyol\t1-4\tGirona FC\nBadalona\t1-1\tCerdanyola\nOlot\t1-2\tVilafranca\nRCD Espanyol\t4-4\tBadalona\nPrat\t2-3\tVilafranca\nManlleu\t4-5\tCerdanyola\nSabadell\t1-0\tTerrassa\nRCD Espanyol\t4-4\tManlleu\nManlleu\t2-3\tReus Deportiu\nCornell\xc3\xa0\t5-2\tN\xc3\xa0stic de Tarragona\nSant Andreu\t0-5\tBadalona\nCornell\xc3\xa0\t5-2\tSabadell\nTerrassa\t0-3\tGirona FC\nSabadell\t4-3\tTerrassa\nLleida Esportiu\t1-1\tBadalona\nCornell\xc3\xa0\t1-2\tReus Deportiu\nManlleu\t5-3\tEuropa\nLleida Esportiu\t5-0\tRCD Espanyol\nFigueres\t0-4\tGranollers\nPrat\t1-5\tFC Barcelona\nManlleu\t0-5\tSabadell\nSabadell\t5-4\tVilafranca\nSant Andreu\t0-2\tLleida Esportiu\nManlleu\t1-2\tRCD Espanyol\nFigueres\t5-5\tReus Deportiu\nRCD Espanyol\t0-2\tN\xc3\xa0stic de Tarragona\nCerdanyola\t1-2\tGirona FC\nFigueres\t2-4\tRCD Espanyol\nOlot\t3-4\tRCD Espanyol\nFC Barcelona\t4-0\tBadalona\nGranollers\t2-4\tSabadell\nReus Deportiu\t1-0\tFigueres\nPrat\t3-4\tLleida Esportiu\nSabadell\t0-5\tFigueres\nVilafranca\t2-3\tCornell\xc3\xa0\nLlagostera\t3-5\tCornell\xc3\xa0\nSant Andreu\t3-4\tGranollers\nFigueres\t4-2\tEuropa\nGirona FC\t2-4\tBadalona\nGirona FC\t4-1\tCerdanyola\nCerdanyola\t3-4\tVilafranca\nBadalona\t5-1\tVilafranca\nManlleu\t0-2\tFigueres\nFigueres\t0-0\tFC Barcelona\nReus Deportiu\t3-3\tPrat\nCerdanyola\t5-0\tTerrassa\nSabadell\t2-3\tLleida Esportiu\nGirona FC\t5-1\tSant Andreu\nFC Barcelona\t4-0\tVilafranca\nLlagostera\t3-0\tOlot\nSabadell\t1-5\tCornell\xc3\xa0\nLlagostera\t3-1\tManlleu\nGranollers\t2-3\tRCD Espanyol\nPrat\t3-4\tCornell\xc3\xa0\nTerrassa\t4-4\tOlot\nReus Deportiu\t3-5\tSant Andreu\nN\xc3\xa0stic de Tarragona\t4-0\tRCD Espanyol\nLlagostera\t2-4\tTerrassa\nGirona FC\t3-2\tTerrassa\nCornell\xc3\xa0\t4-1\tRCD Espanyol\nTerrassa\t3-2\tCerdanyola\nGirona FC\t0-4\tFC Barcelona\nLleida Esportiu\t3-4\tLlagostera\nLlagostera\t5-0\tReus Deportiu\nFigueres\t3-5\tN\xc3\xa0stic de Tarragona\nOlot\t2-0\tGranollers\nVilafranca\t1-4\tLleida Esportiu\nN\xc3\xa0stic de Tarragona\t2-5\tGirona FC\nCerdanyola\t3-3\tN\xc3\xa0stic de Tarragona\nPrat\t5-0\tManlleu\nCornell\xc3\xa0\t0-4\tCerdanyola\nN\xc3\xa0stic de Tarragona\t3-0\tCornell\xc3\xa0\nFC Barcelona\t4-0\tSant Andreu\nCerdanyola\t2-3\tSabadell\nFC Barcelona\t5-4\tGranollers\nOlot\t3-3\tSant Andreu\nEuropa\t5-2\tVilafranca\nRCD Espanyol\t1-1\tVilafranca\nSabadell\t3-1\tOlot\nLleida Esportiu\t0-0\tBadalona\nEuropa\t2-3\tOlot\nGranollers\t0-1\tTerrassa\nBadalona\t3-5\tN\xc3\xa0stic de Tarragona\nSant Andreu\t2-0\tN\xc3\xa0stic de Tarragona\nCerdanyola\t1-2\tFigueres\nRCD Espanyol\t5-3\tCerdanyola\nEuropa\t0-3\tGirona FC\nSabadell\t2-5\tRCD Espanyol\nCerdanyola\t2-5\tSabadell\nPrat\t5-0\tCornell\xc3\xa0\nGranollers\t3-4\tTerrassa\nReus Deportiu\t5-2\tPrat\nSabadell\t3-1\tManlleu\nCerdanyola\t3-4\tFigueres\nTerrassa\t5-1\tLleida Esportiu\nCornell\xc3\xa0\t2-0\tLleida Esportiu\nCerdanyola\t2-1\tFigueres\nFigueres\t5-3\tReus Deportiu\nRCD Espanyol\t1-1\tGranollers\nFC Barcelona\t1-5\tLlagostera\nReus Deportiu\t5-5\tLleida Esportiu\nVilafranca\t3-0\tManlleu\nPrat\t0-1\tReus Deportiu\nSant Andreu\t5-2\tGranollers\nTerrassa\t2-2\tBadalona\nEuropa\t5-5\tManlleu\nEuropa\t4-4\tFC Barcelona\nPrat\t2-0\tGranollers\nReus Deportiu\t3-0\tFigueres\nN\xc3\xa0stic de Tarragona\t5-4\tCerdanyola\nVilafranca\t4-0\tSant Andreu\nLlagostera\t1-1\tCornell\xc3\xa0\nOlot\t4-0\tN\xc3\xa0stic de Tarragona\nCornell\xc3\xa0\t1-4\tGirona FC\nGirona FC\t4-0\tFC Barcelona\nGirona FC\t3-5\tLleida Esportiu\nPrat\t5-3\tGranollers\nManlleu\t0-5\tGranollers\nOlot\t0-3\tBadalona\nSabadell\t4-3\tPrat\nN\xc3\xa0stic de Tarragona\t4-2\tPrat\nCerdanyola\t1-2\tFigueres\nCornell\xc3\xa0\t4-5\tVilafranca\nLlagostera\t5-2\tTerrassa\nLlagostera\t1-4\tFigueres\nTerrassa\t3-5\tLlagostera\nVilafranca\t2-4\tCornell\xc3\xa0\nLlagostera\t2-0\tSant Andreu\nCerdanyola\t0-5\tFC Barcelona\nRCD Espanyol\t1-1\tLleida Esportiu\nN\xc3\xa0stic de Tarragona\t2-0\tSant Andreu\nSabadell\t5-1\tCornell\xc3\xa0\nLlagostera\t3-1\tCornell\xc3\xa0\nGranollers\t5-0\tManlleu\nEuropa\t4-0\tRCD Espanyol\nCornell\xc3\xa0\t0-3\tReus Deportiu\nTerrassa\t2-3\tOlot\nLleida Esportiu\t2-1\tSabadell\nLlagostera\t2-4\tManlleu\nFC Barcelona\t2-5\tRCD Espanyol\nCerdanyola\t2-4\tN\xc3\xa0stic de Tarragona\nRCD Espanyol\t1-3\tLlagostera\nCornell\xc3\xa0\t2-0\tCerdanyola\nN\xc3\xa0stic de Tarragona\t5-0\tFC Barcelona\nReus Deportiu\t3-3\tSabadell\nManlleu\t3-1\tLlagostera\nOlot\t3-3\tFigueres\nGirona FC\t0-2\tOlot\nManlleu\t2-2\tFigueres\nBadalona\t1-0\tVilafranca\nRCD Espanyol\t5-4\tFigueres\nLlagostera\t4-0\tSant Andreu\nReus Deportiu\t0-3\tLlagostera\nGirona FC\t2-0\tPrat\nFigueres\t5-2\tReus Deportiu\nGranollers\t4-2\tLleida Esportiu\nN\xc3\xa0stic de Tarragona\t2-2\tVilafranca\nVilafranca\t2-1\tGranollers\nSant Andreu\t5-5\tSabadell\nLlagostera\t3-5\tCornell\xc3\xa0\nGirona FC\t2-4\tFigueres\nFC Barcelona\t2-0\tPrat\nManlleu\t2-2\tBadalona\nReus Deportiu\t5-3\tTerrassa\nFigueres\t4-5\tLlagostera\nTerrassa\t4-4\tBadalona\nManlleu\t0-4\tSant Andreu\nRCD Espanyol\t2-0\tN\xc3\xa0stic de Tarragona\nCornell\xc3\xa0\t0-5\tPrat\nLleida Esportiu\t4-2\tSant Andreu\nRCD Espanyol\t3-1\tN\xc3\xa0stic de Tarragona\nSabadell\t1-0\tGranollers\nFC Barcelona\t5-5\tPrat\nCerdanyola\t0-1\tGirona FC\nPrat\t2-4\tSant Andreu\nVilafranca\t1-1\tRCD Espanyol\nCerdanyola\t5-0\tTerrassa\nFC Barcelona\t0-5\tCornell\xc3\xa0\nManlleu\t3-0\tCerdanyola\nSabadell\t1-4\tVilafranca\nLlagostera\t0-5\tLleida Esportiu\nN\xc3\xa0stic de Tarragona\t2-2\tSant Andreu\nPrat\t0-0\tRCD Espanyol\nCerdanyola\t2-5\tLleida Esportiu\nManlleu\t5-0\tGirona FC\nGranollers\t4-5\tRCD Espanyol\nBadalona\t2-4\tOlot\nLleida Esportiu\t2-3\tGirona FC\nFigueres\t3-1\tBadalona\nTerrassa\t4-5\tCornell\xc3\xa0\nRCD Espanyol\t1-2\tEuropa\nEuropa\t0-1\tVilafranca\nN\xc3\xa0stic de Tarragona\t2-5\tFigueres\nSant Andreu\t1-5\tManlleu\nEuropa\t5-3\tFC Barcelona\nSant Andreu\t1-3\tLleida Esportiu\nCerdanyola\t2-4\tBadalona\nSant Andreu\t4-0\tTerrassa\nSabadell\t4-3\tEuropa\nBadalona\t3-1\tN\xc3\xa0stic de Tarragona\nGranollers\t4-1\tVilafranca\nReus Deportiu\t4-1\tVilafranca\nPrat\t1-5\tGranollers\nRCD Espanyol\t0-5\tN\xc3\xa0stic de Tarragona\nBadalona\t0-2\tSabadell\nGirona FC\t3-3\tBadalona\nTerrassa\t1-0\tSabadell\nLleida Esportiu\t2-5\tFigueres\nOlot\t2-2\tFigueres\nRCD Espanyol\t0-4\tLlagostera\nBadalona\t5-0\tFigueres\nPrat\t1-2\tOlot\nCerdanyola\t0-2\tLleida Esportiu\nFC Barcelona\t2-5\tFigueres\nTerrassa\t5-5\tBadalona\nN\xc3\xa0stic de Tarragona\t5-4\tBadalona\nN\xc3\xa0stic de Tarragona\t0-4\tTerrassa\nSant Andreu\t3-4\tN\xc3\xa0stic de Tarragona\nCornell\xc3\xa0\t3-3\tReus Deportiu\nCerdanyola\t4-1\tManlleu\nSabadell\t3-3\tN\xc3\xa0stic de Tarragona\nReus Deportiu\t4-5\tN\xc3\xa0stic de Tarragona\nCerdanyola\t2-0\tFC Barcelona\nN\xc3\xa0stic de Tarragona\t2-3\tRCD Espanyol\nEuropa\t4-2\tBadalona\nCornell\xc3\xa0\t3-4\tRCD Espanyol\nSabadell\t1-1\tGranollers\nGirona FC\t5-2\tOlot\nFC Barcelona\t5-2\tN\xc3\xa0stic de Tarragona\nN\xc3\xa0stic de Tarragona\t2-5\tFigueres\nVilafranca\t2-0\tFC Barcelona\nEuropa\t2-3\tLleida Esportiu\nRCD Espanyol\t5-2\tOlot\nLleida Esportiu\t0-1\tN\xc3\xa0stic de Tarragona\nPrat\t1-0\tOlot\nTerrassa\t5-2\tEuropa\nLlagostera\t0-5\tN\xc3\xa0stic de Tarragona\nN\xc3\xa0stic de Tarragona\t3-2\tReus Deportiu\nReus Deportiu\t1-4\tLlagostera\nSabadell\t0-4\tBadalona\nVilafranca\t2-1\tLleida Esportiu\nLlagostera\t0-2\tTerrassa\nGirona FC\t5-5\tVilafranca\nGranollers\t4-4\tOlot\nGirona FC\t3-0\tCerdanyola\nFC Barcelona\t1-1\tCerdanyola\nBadalona\t5-5\tReus Deportiu\nCornell\xc3\xa0\t4-4\tFigueres\nGirona FC\t5-4\tFigueres\nSabadell\t5-3\tFC Barcelona\nN\xc3\xa0stic de Tarragona\t0-4\tGirona FC\nTerrassa\t3-2\tReus Deportiu\nReus Deportiu\t1-1\tEuropa\nTerrassa\t5-5\tLlagostera\nPrat\t4-1\tCornell\xc3\xa0\nSant Andreu\t3-0\tPrat\nPrat\t1-3\tCerdanyola\nSabadell\t5-0\tFigueres\nOlot\t1-1\tManlleu\nReus Deportiu\t0-1\tTerrassa\nSant Andreu\t2-2\tTerrassa\nN\xc3\xa0stic de Tarragona\t2-4\tSabadell\nLlagostera\t3-5\tCerdanyola\nGranollers\t3-1\tBadalona\nFigueres\t4-0\tReus Deportiu\nEuropa\t4-5\tLlagostera\nGirona FC\t2-4\tTerrassa\nOlot\t1-2\tGranollers\nVilafranca\t5-5\tOlot\nRCD Espanyol\t4-2\tFigueres\nTerrassa\t3-3\tFigueres\nGirona FC\t5-2\tSabadell\nSabadell\t3-3\tCornell\xc3\xa0\nGranollers\t0-2\tGirona FC\nOlot\t0-4\tFC Barcelona\nEuropa\t4-4\tGirona FC\nLleida Esportiu\t5-4\tVilafranca\nReus Deportiu\t2-4\tSabadell\nSant Andreu\t5-2\tOlot\nLleida Esportiu\t2-2\tGranollers\nLlagostera\t4-2\tGranollers\nTerrassa\t0-2\tLlagostera\nLleida Esportiu\t5-3\tBadalona\nSabadell\t3-5\tFigueres\nN\xc3\xa0stic de Tarragona\t3-4\tSabadell\nEuropa\t0-5\tCerdanyola\nCornell\xc3\xa0\t4-5\tManlleu\nReus Deportiu\t5-1\tLleida Esportiu\nVilafranca\t1-0\tRCD Espanyol\nRCD Espanyol\t4-5\tGirona FC\nGranollers\t4-0\tVilafranca\nSant Andreu\t2-4\tReus Deportiu\nLleida Esportiu\t1-2\tFC Barcelona\nLlagostera\t4-4\tSant Andreu\nGirona FC\t2-4\tLlagostera\nFigueres\t0-4\tReus Deportiu\nLleida Esportiu\t1-5\tRCD Espanyol\nPrat\t2-0\tSant Andreu\nBadalona\t0-1\tSant Andreu\nOlot\t1-2\tReus Deportiu\nSabadell\t1-4\tSant Andreu\nSant Andreu\t0-1\tLleida Esportiu\nFC Barcelona\t3-2\tLleida Esportiu\nBadalona\t3-0\tLlagostera\nLlagostera\t0-2\tCornell\xc3\xa0\nCornell\xc3\xa0\t3-1\tOlot\nN\xc3\xa0stic de Tarragona\t0-1\tCornell\xc3\xa0\nGirona FC\t4-1\tRCD Espanyol\nVilafranca\t4-4\tLlagostera\nN\xc3\xa0stic de Tarragona\t3-4\tFC Barcelona\nN\xc3\xa0stic de Tarragona\t0-2\tCornell\xc3\xa0\nTerrassa\t0-0\tManlleu\nSabadell\t3-3\tTerrassa\nN\xc3\xa0stic de Tarragona\t2-2\tVilafranca\nSabadell\t4-4\tFigueres\nRCD Espanyol\t2-0\tPrat\nCornell\xc3\xa0\t1-2\tTerrassa\nPrat\t0-0\tBadalona\nFigueres\t0-2\tGranollers\nManlleu\t5-0\tFC Barcelona\nSant Andreu\t3-5\tReus Deportiu\nRCD Espanyol\t2-1\tBadalona\nSant Andreu\t5-0\tCornell\xc3\xa0\nOlot\t4-5\tFC Barcelona\nOlot\t5-1\tFigueres\nPrat\t3-1\tCornell\xc3\xa0\nOlot\t3-1\tFigueres\nOlot\t2-4\tGirona FC\nSabadell\t5-3\tCerdanyola\nLlagostera\t3-5\tManlleu\nGranollers\t2-4\tBadalona\nRCD Espanyol\t4-5\tCerdanyola\nLlagostera\t4-4\tSant Andreu\nFC Barcelona\t5-3\tVilafranca\nLleida Esportiu\t2-1\tReus Deportiu\nGranollers\t2-1\tCerdanyola\nEuropa\t0-3\tManlleu\nGranollers\t4-5\tRCD Espanyol\nFC Barcelona\t4-5\tN\xc3\xa0stic de Tarragona\nManlleu\t3-3\tRCD Espanyol\nSabadell\t4-5\tManlleu\nEuropa\t2-0\tReus Deportiu\nOlot\t4-0\tGranollers\nTerrassa\t3-1\tRCD Espanyol\nVilafranca\t2-5\tTerrassa\nReus Deportiu\t0-5\tSant Andreu\nN\xc3\xa0stic de Tarragona\t4-0\tRCD Espanyol\nPrat\t4-4\tSant Andreu\nTerrassa\t5-3\tVilafranca\nFC Barcelona\t3-0\tLlagostera\nGranollers\t5-0\tOlot\nFigueres\t4-5\tVilafranca\nTerrassa\t3-3\tLlagostera\nPrat\t3-3\tRCD Espanyol\nN\xc3\xa0stic de Tarragona\t1-4\tLlagostera\nOlot\t4-4\tVilafranca\nOlot\t0-3\tGranollers\nBadalona\t3-3\tLlagostera\nEuropa\t1-5\tOlot\nCornell\xc3\xa0\t2-2\tSant Andreu\nGirona FC\t5-1\tLleida Esportiu\nReus Deportiu\t5-2\tSant Andreu\nVilafranca\t0-4\tLleida Esportiu\nFC Barcelona\t1-5\tLlagostera\nBadalona\t3-4\tTerrassa\nFC Barcelona\t1-1\tRCD Espanyol\nSant Andreu\t5-4\tTerrassa\nSabadell\t0-1\tGirona FC\nRCD Espanyol\t1-3\tPrat\nN\xc3\xa0stic de Tarragona\t3-3\tPrat\nFC Barcelona\t5-2\tPrat\nRCD Espanyol\t1-4\tCerdanyola\nTerrassa\t1-2\tSant Andreu\nLlagostera\t5-4\tEuropa\nLleida Esportiu\t1-5\tFigueres\nN\xc3\xa0stic de Tarragona\t1-3\tGirona FC\nCornell\xc3\xa0\t5-2\tBadalona\nOlot\t3-0\tLleida Esportiu\nGranollers\t5-3\tManlleu\nGranollers\t1-3\tLlagostera\nSabadell\t5-3\tOlot\nReus Deportiu\t3-1\tTerrassa\nPrat\t3-3\tRCD Espanyol\nRCD Espanyol\t5-1\tN\xc3\xa0stic de Tarragona\nSant Andreu\t0-0\tTerrassa\nCornell\xc3\xa0\t5-0\tTerrassa\nVilafranca\t4-5\tCornell\xc3\xa0\nVilafranca\t4-5\tBadalona\nFC Barcelona\t4-3\tLleida Esportiu\nTerrassa\t5-4\tCornell\xc3\xa0\nOlot\t1-5\tEuropa\nLleida Esportiu\t4-5\tFigueres\nSant Andreu\t5-0\tEuropa\nSant Andreu\t3-1\tGirona FC\nSabadell\t1-3\tLlagostera\nN\xc3\xa0stic de Tarragona\t1-3\tOlot\nBadalona\t5-4\tPrat\nOlot\t4-5\tLlagostera\nFC Barcelona\t3-1\tCornell\xc3\xa0\nOlot\t0-5\tGranollers\n'}

**FUNCIÓN** *historico_dataframe*:
1. Convertimos el archivo a dataframe.
2. Renombramos las columnas
3. Dividimos la colmuna "resultados" en 2: goles por equipo.
4. Eliminamos la columna "resultados".
5. Ordenamos la columnas del dataframe para visulizar mejor los datos.
6. Devuelve el dataframe.

In [ ]:
def historico_dataframe(archivo):

  #convertir a dataframe
  archivo = pd.read_csv("historic_partits.txt", sep="\t")

  # definir las columnas
  archivo.columns = ["equipo_local", "resultado", "equipo_visitante"]

  # dividir la columna "resultados" en 2
  archivo[["goles_local", "goles_visitante"]] = archivo["resultado"].str.split("-", expand=True)

  #eliminamos la columna de "resultados"
  df = archivo.drop(columns=["resultado"])

  # ordenamos las columnas
  orden = ["equipo_local", "goles_local", "goles_visitante", "equipo_visitante"]

  # Aplica el nuevo orden al DataFrame
  df = df[orden]

  return df

In [ ]:
#comprobamos

subido = subir_historico()

df_historico = historico_dataframe(subido)

display(df_historico)

Saving historic_partits.txt to historic_partits (1).txt

            equipo_local goles_local goles_visitante equipo_visitante
0             Vilafranca           4               5         Terrassa
1                   Olot           5               0       Granollers
2             Vilafranca           5               5          Manlleu
3               Cornellà           5               1             Prat
4             Cerdanyola           0               5       Vilafranca
..                   ...         ...             ...              ...
494  Nàstic de Tarragona           1               3             Olot
495             Badalona           5               4             Prat
496                 Olot           4               5       Llagostera
497         FC Barcelona           3               1         Cornellà
498                 Olot           0               5       Granollers

[499 rows x 4 columns]

**FUNCIÓN** *calcular_puntos*:
1. Calcular: empates, ganados y perdidos con il/elif en numpy --> where del equipo local.
2. Hacer el mismo calcular del equipo visitante.
3. Creamos un dataframe para "locales" y otro para "visitantes" con los puntos.
4. Combinamos/juntamos las 2 tablas en una sola agrupando por equipo y sumando los puntos.
5. Devolvemos y guardamos el dataframe creado.

In [ ]:
def calcular_puntos(df):

  # Puntos local (3 si gana, 1 si empata, 0 si pierde)
  df["pts_local"] = np.where(df["goles_local"] > df["goles_visitante"], 3,
                    np.where(df["goles_local"] == df['goles_visitante'], 1, 0))

  # Puntos visitante (3 si gana, 1 si empata, 0 si pierde)
  df["pts_visitante"] = np.where(df["goles_visitante"] > df["goles_local"], 3,
                        np.where(df["goles_local"] == df["goles_visitante"], 1, 0))

  #creamos un dataframe con los puntos por equipo

  # primero creamos un dataframe por cada equipo: local y visitante
  locales = df[["equipo_local", "pts_local"]].rename(columns={"equipo_local": "equipo", "pts_local": "puntos"})
  visitantes = df[["equipo_visitante", "pts_visitante"]].rename(columns={"equipo_visitante": "equipo", "pts_visitante": "puntos"})

  #combinamos ambas tablas en una sola.
  df_puntos = (pd.concat([locales, visitantes]) #unimos las 2 tablas
            .groupby("equipo", as_index=False)["puntos"] # agrupamos por equipo
            .sum()  #sumamos los puntos
            .sort_values("puntos", ascending=False) #ordenamos de mayor a menos
            .reset_index(drop=True))

  return df_puntos

In [ ]:
#comprobamos
calcular_puntos(df_historico)

                 equipo  puntos
0             Girona FC      96
1            Llagostera      94
2              Sabadell      85
3              Cornellà      82
4          RCD Espanyol      80
5              Figueres      79
6       Lleida Esportiu      75
7              Terrassa      74
8          FC Barcelona      73
9            Vilafranca      72
10             Badalona      68
11        Reus Deportiu      68
12  Nàstic de Tarragona      68
13           Granollers      64
14                 Olot      64
15          Sant Andreu      62
16              Manlleu      57
17           Cerdanyola      56
18                 Prat      56
19               Europa      41

**FUNCIÓN** *calcular_goles*:

Sumamos los goles en contra y a favor de cada equipo.
1. Convertimos a "*int*" porque el valor de las columnas no es numérico.
2. Hacemos 2 dataframe: uno de locales y otro de visitantes. Renombramos las columnas segun los goles a favor o en contra.
3. Juntamos ambas tablas agrupando por equipo y sumando los goles.
4. Nos guarda y devuleve el dataframe.

In [ ]:
def calcular_goles(df):

  # Convertir a int, porque si no, acumula los resultados, no los suma.
  df["goles_local"]     = pd.to_numeric(df["goles_local"])
  df["goles_visitante"] = pd.to_numeric(df["goles_visitante"])


  # Goles como local
  locales = df[["equipo_local", "goles_local", "goles_visitante"]].rename(columns={
      "equipo_local":    "equipo",
      "goles_local":     "goles_favor",
      "goles_visitante": "goles_contra"
  })

  # Goles como visitante
  visitantes = df[["equipo_visitante", "goles_visitante", "goles_local"]].rename(columns={
      "equipo_visitante": "equipo",
      "goles_visitante":  "goles_favor",
      "goles_local":      "goles_contra"
  })

  # Concatenar y sumar
  df_goles = (pd.concat([locales, visitantes])
            .groupby("equipo", as_index=False)[["goles_favor", "goles_contra"]]
            .sum()
            .sort_values("goles_favor", ascending=False)
            .reset_index(drop=True))

  return df_goles

In [ ]:
#comprobamos
calcular_goles(df_historico)

                 equipo  goles_favor  goles_contra
0              Figueres          161           154
1            Llagostera          159           142
2            Vilafranca          157           172
3              Cornellà          147           146
4              Terrassa          147           164
5              Sabadell          141           121
6             Girona FC          139            94
7              Badalona          134           124
8                  Olot          132           144
9          RCD Espanyol          131           144
10  Nàstic de Tarragona          130           148
11      Lleida Esportiu          129           133
12         FC Barcelona          125           115
13          Sant Andreu          123           134
14           Granollers          121           117
15        Reus Deportiu          119           111
16           Cerdanyola          117           133
17              Manlleu          106           117
18                 Prat          106           111
19               Europa           93            93

**FUNCIÓN** *calcular_partidos*:

Calculamos los partidos ganados, empatados y perdidos.
1. Hacemos un dataframe solo con los equipos locales renombrando las columnas de los resultados.
2. Hacemos un dataframe solo con los equipos visitantes renombrando las columnas de los resultados.
3. Unimos las 2 tablas.
4. Establecemos las condiciones:
*   Si goles a favor es mayor que goles en contra --> suma 1 en la columna *ganados*.
*   Si goles a favor es igual que goles en contra --> suma 1 en la columna *empatados*.
*   Si goles a favor es menor que goles en contra --> suma 1 en la columna *perdidos*.

5. Agrupamos el dataframe por equipo, sumamos y ordenamos los resultados.
6. Devuelve el dataframe.

In [ ]:
def calcular_partidos(df):

  # hacemos un dataframe on los equipos locases
  locales = df[["equipo_local", "goles_local", "goles_visitante"]].copy()
  locales.columns = ["equipo", "favor", "contra"]

  # hacemos un df con los visitantes
  visitantes = df[["equipo_visitante", "goles_visitante", "goles_local"]].copy()
  visitantes.columns = ["equipo", "favor", "contra"]

  # Unimos los dos fd
  todos = pd.concat([locales, visitantes]).reset_index(drop=True)

  # utilizamos condicionales para calcular el resultado
  condiciones = [
      todos["favor"] > todos["contra"],
      todos["favor"] == todos["contra"],
      todos["favor"] < todos["contra"]
  ]

  todos["ganados"]   = np.select(condiciones, [1, 0, 0])
  todos["empatados"] = np.select(condiciones, [0, 1, 0])
  todos["perdidos"]  = np.select(condiciones, [0, 0, 1])

  # agrupamos el dataframe por equipo y summos los resutlados anteriores
  df_partidos = (todos.groupby("equipo", as_index=False)[["ganados", "empatados", "perdidos"]]
                .sum()
                .sort_values("ganados", ascending=False)
                .reset_index(drop=True))

  return df_partidos

In [ ]:
#comprobamos
calcular_partidos(df_historico)

                 equipo  ganados  empatados  perdidos
0             Girona FC       31          3        13
1            Llagostera       29          7        20
2              Sabadell       26          7        15
3              Cornellà       25          7        22
4          RCD Espanyol       23         11        21
5              Figueres       23         10        23
6       Lleida Esportiu       23          6        23
7          FC Barcelona       22          7        15
8            Vilafranca       20         12        25
9   Nàstic de Tarragona       20          8        27
10             Terrassa       20         14        23
11           Granollers       20          4        24
12        Reus Deportiu       20          8        16
13                 Olot       18         10        26
14             Badalona       18         14        16
15           Cerdanyola       17          5        28
16          Sant Andreu       17         11        25
17              Manlleu       16          9        17
18                 Prat       16          8        21
19               Europa       12          5        16

**FUNCIÓN** *combinar_resultados*():
  
Juntamos todos los df en uno solo.
1. Recibe 3 dataframes.
2. Los combina en uno solo.
3. Ordenamos las columnas del dataframe par que siempre devuelva el mismo orden.
4. Devuelve el df final.

In [ ]:
def combinar_resultados(df1, df2, df3):
  df_clasificacion = df1 \
      .merge(df2, on="equipo", how="outer") \
      .merge(df3,    on="equipo", how="outer")
       #con outer, aparecen todos los equipos aunque no aparezcan en los tres dataframe.

  #ordenamos las columnas, porque según el orden de los df como variables, puede verse afectado.
  orden = ["equipo", "goles_favor", "goles_contra", "ganados", "perdidos", "empatados", "puntos"]
  df_clasificacion = df_clasificacion[orden]

  return df_clasificacion

In [ ]:
#comprobamos
goles = calcular_goles(df_historico)
partidos = calcular_partidos(df_historico)
puntos = calcular_puntos(df_historico)

final = combinar_resultados(puntos, partidos, goles)
display(final)

,equipo,goles_favor,goles_contra,ganados,perdidos,empatados,puntos
0,Badalona,134,124,18,16,14,68
1,Cerdanyola,117,133,17,28,5,56
2,Cornellà,147,146,25,22,7,82
3,Europa,93,93,12,16,5,41
4,FC Barcelona,125,115,22,15,7,73
5,Figueres,161,154,23,23,10,79
6,Girona FC,139,94,31,13,3,96
7,Granollers,121,117,20,24,4,64
8,Llagostera,159,142,29,20,7,94
9,Lleida Esportiu,129,133,23,23,6,75
10,Manlleu,106,117,16,17,9,57
11,Nàstic de Tarragona,130,148,20,27,8,68
12,Olot,132,144,18,26,10,64
13,Prat,106,111,16,21,8,56
14,RCD Espanyol,131,144,23,21,11,80
15,Reus Deportiu,119,111,20,16,8,68
16,Sabadell,141,121,26,15,7,85
17,Sant Andreu,123,134,17,25,11,62
18,Terrassa,147,164,20,23,14,74
19,Vilafranca,157,172,20,25,12,72

**FUNCIÓN** *respuestas_clasificacion*():
1. ¿Cuál es el equipo más goleador?
2. ¿Qué equipo ha sido el más goleado?
3. Clasificacion enumerada de los equipos.

In [ ]:
def respuestas_clasificacion(df):

  print("----------------------------------------")
  # EQUIPO MAS GOLEADOR
  equipo_mas_goleador = df.loc[df["goles_favor"].idxmax(), "equipo"]
  print("Equipo más goleador: ", equipo_mas_goleador)  # Figueres (161 goles)
  print("----------------------------------------")

  # EQUIPO MAS GOLEADO
  equipo_mas_goleado = df.loc[df["goles_contra"].idxmax(), "equipo"]
  print("Equipo más goleado: ", equipo_mas_goleado)  # Vilafranca (172 goles)
  print("----------------------------------------")

  # CLASIFICACIÓN
  print("Clasificación final:")
  for i, equipo in enumerate(df["equipo"], start=1):
      print(f"{i}. {equipo}")

  print("----------------------------------------")

In [ ]:
#comprobamos
respuestas_clasificacion(final)

----------------------------------------
Equipo más goleador:  Figueres
----------------------------------------
Equipo más goleado:  Vilafranca
----------------------------------------
Clasificación final:
1. Badalona
2. Cerdanyola
3. Cornellà
4. Europa
5. FC Barcelona
6. Figueres
7. Girona FC
8. Granollers
9. Llagostera
10. Lleida Esportiu
11. Manlleu
12. Nàstic de Tarragona
13. Olot
14. Prat
15. RCD Espanyol
16. Reus Deportiu
17. Sabadell
18. Sant Andreu
19. Terrassa
20. Vilafranca
----------------------------------------

**FUNCIÓN** *main_partidos*():

1. Llamar una a una a todas las funciones y asignarles una variables para que sea mas sencillo y eficaz utilizarlas
2. Motrar las respuestas que nos piden.
3. Mostrar el dataframe final.
4. Guardar y devoler el dataframe

In [ ]:
def main_partidos():

  subido = subir_historico()
  df_historico = historico_dataframe(subido)
  goles = calcular_goles(df_historico)
  partidos = calcular_partidos(df_historico)
  puntos = calcular_puntos(df_historico)

  final = combinar_resultados(puntos, partidos, goles)
  respuestas_clasificacion(final)

  display(final)

  return final

COMPROBAMOS QUE NUESTRA FUNCIÓN FINAL FUNCIONA

In [ ]:
# COMPROBACIÓN FINAL

main_partidos()

Saving historic_partits.txt to historic_partits (2).txt
----------------------------------------
Equipo más goleador:  Figueres
----------------------------------------
Equipo más goleado:  Vilafranca
----------------------------------------
Clasificación final:
1. Badalona
2. Cerdanyola
3. Cornellà
4. Europa
5. FC Barcelona
6. Figueres
7. Girona FC
8. Granollers
9. Llagostera
10. Lleida Esportiu
11. Manlleu
12. Nàstic de Tarragona
13. Olot
14. Prat
15. RCD Espanyol
16. Reus Deportiu
17. Sabadell
18. Sant Andreu
19. Terrassa
20. Vilafranca
----------------------------------------

,equipo,goles_favor,goles_contra,ganados,perdidos,empatados,puntos
0,Badalona,134,124,18,16,14,68
1,Cerdanyola,117,133,17,28,5,56
2,Cornellà,147,146,25,22,7,82
3,Europa,93,93,12,16,5,41
4,FC Barcelona,125,115,22,15,7,73
5,Figueres,161,154,23,23,10,79
6,Girona FC,139,94,31,13,3,96
7,Granollers,121,117,20,24,4,64
8,Llagostera,159,142,29,20,7,94
9,Lleida Esportiu,129,133,23,23,6,75
10,Manlleu,106,117,16,17,9,57
11,Nàstic de Tarragona,130,148,20,27,8,68
12,Olot,132,144,18,26,10,64
13,Prat,106,111,16,21,8,56
14,RCD Espanyol,131,144,23,21,11,80
15,Reus Deportiu,119,111,20,16,8,68
16,Sabadell,141,121,26,15,7,85
17,Sant Andreu,123,134,17,25,11,62
18,Terrassa,147,164,20,23,14,74
19,Vilafranca,157,172,20,25,12,72

,equipo,goles_favor,goles_contra,ganados,perdidos,empatados,puntos
0,Badalona,134,124,18,16,14,68
1,Cerdanyola,117,133,17,28,5,56
2,Cornellà,147,146,25,22,7,82
3,Europa,93,93,12,16,5,41
4,FC Barcelona,125,115,22,15,7,73
5,Figueres,161,154,23,23,10,79
6,Girona FC,139,94,31,13,3,96
7,Granollers,121,117,20,24,4,64
8,Llagostera,159,142,29,20,7,94
9,Lleida Esportiu,129,133,23,23,6,75
10,Manlleu,106,117,16,17,9,57
11,Nàstic de Tarragona,130,148,20,27,8,68
12,Olot,132,144,18,26,10,64
13,Prat,106,111,16,21,8,56
14,RCD Espanyol,131,144,23,21,11,80
15,Reus Deportiu,119,111,20,16,8,68
16,Sabadell,141,121,26,15,7,85
17,Sant Andreu,123,134,17,25,11,62
18,Terrassa,147,164,20,23,14,74
19,Vilafranca,157,172,20,25,12,72

**SPRINT 7 FINALIZADO**

Creació de funcions, estructures de dades i bucles

*SILVIA VILCHES*